version: "3.9"

services:
  scylla:
    image: scylladb/scylla:2025.3
    container_name: tessaro-scylla
    command: ["--smp", "1", "--memory", "750M"]
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local' 127.0.0.1 9042"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - scylla-data:/var/lib/scylla

  scylla-init:
    image: scylladb/scylla:2025.3
    container_name: tessaro-scylla-init
    depends_on:
      - scylla
    volumes:
      - ./infra/docker/scylla-init.cql:/init/scylla-init.cql:ro
    entrypoint: ["/bin/sh", "-c", "until cqlsh scylla 9042 -e 'SELECT now() FROM system.local'; do sleep 5; done; cqlsh scylla 9042 -f /init/scylla-init.cql"]
    restart: "on-failure"

  users-api:
    build:
      context: .
      dockerfile: services/users-api/functions/Dockerfile
    container_name: tessaro-users-api
    depends_on:
      - scylla
      - scylla-init
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      FUNCTION_ENTRY: services/users-api/functions/src/server.ts
      SCYLLA_CONTACT_POINTS: scylla
      SCYLLA_LOCAL_DC: datacenter1
      SCYLLA_KEYSPACE: tessaro_admin
      CORS_ALLOWED_ORIGINS: http://localhost:4173
    ports:
      - "8080:8080"

  admin-app:
    build:
      context: .
      dockerfile: services/admin-app/app/Dockerfile
    container_name: tessaro-admin-app
    depends_on:
      - users-api
    environment:
      VITE_USERS_API_URL: http://users-api:8080
    ports:
      - "4173:4173"

volumes:
  scylla-data:
