services:
  admin-app:
    build:
      context: .
      dockerfile: services/admin-app/app/Dockerfile
    environment:
      VITE_USERS_API_URL: http://api-server:8080
    ports:
      - "4173:4173"
    depends_on:
      - api-server

  api-server:
    build:
      context: .
      dockerfile: services/api-server/Dockerfile
    environment:
      PORT: 8080
      SQLITE_PATH: /app/data/admin.sqlite
      DENO_KV_PATH: /app/data/kv.sqlite
    ports:
      - "8080:8080"
    volumes:
      - ./services/api-server/data:/app/data
