apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: scylla-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: scylla
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: scylla-operator
        namespace: scylla-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    manager:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
    webhook:
      enabled: true
