apiVersion: batch/v1
kind: Job
metadata:
  name: scylla-bootstrap
  namespace: databases
  labels:
    app.kubernetes.io/name: scylla-bootstrap
spec:
  backoffLimit: 8
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla-bootstrap
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cqlsh
          image: scylladb/scylla:2025.3
          env:
            - name: SCYLLA_CONTACT_POINT
              value: scylla-client.databases.svc.cluster.local
            - name: SCYLLA_PORT
              value: "9042"
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              echo "Waiting for Scylla to accept CQL connections..."
              until cqlsh "$SCYLLA_CONTACT_POINT" "$SCYLLA_PORT" -e "SELECT cluster_name FROM system.local" >/dev/null 2>&1; do
                sleep 5
              done
              cat <<'CQL' | cqlsh "$SCYLLA_CONTACT_POINT" "$SCYLLA_PORT"
              CREATE KEYSPACE IF NOT EXISTS tessaro_admin
                WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}
                AND durable_writes = true;

              CREATE TABLE IF NOT EXISTS tessaro_admin.users (
                id uuid PRIMARY KEY,
                email text,
                name text,
                role text,
                avatar_url text,
                created_at timestamp,
                updated_at timestamp
              );

              CREATE TABLE IF NOT EXISTS tessaro_admin.organizations (
                id uuid PRIMARY KEY,
                name text,
                plan text,
                status text,
                created_at timestamp,
                updated_at timestamp
              );

              CREATE TABLE IF NOT EXISTS tessaro_admin.services (
                id uuid PRIMARY KEY,
                name text,
                type text,
                status text,
                created_at timestamp,
                updated_at timestamp
              );

              CREATE TABLE IF NOT EXISTS tessaro_admin.audit_logs (
                id uuid PRIMARY KEY,
                action text,
                user_id uuid,
                target_id uuid,
                ip_address text,
                timestamp timestamp,
                metadata text
              );
              CQL
              echo "Scylla bootstrap complete."
      tolerations:
        - operator: "Exists"
