apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: users-api-get
  namespace: apps
  labels:
    app.kubernetes.io/name: users-api-get
    app.kubernetes.io/part-of: tessaro-admin
  annotations:
    networking.knative.dev/ingress-class: kourier.ingress.networking.knative.dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "5"
    spec:
      timeoutSeconds: 30
      containers:
        - name: users-api-get
          image: ghcr.io/your-org/tessaro-users-api-get@sha256:REPLACE_WITH_DIGEST
          imagePullPolicy: IfNotPresent
          env:
            - name: FUNCTION_ENTRY
              value: services/users-api/functions/src/knative-get-users.ts
            - name: PORT
              value: "8080"
            - name: HOST
              value: 0.0.0.0
            - name: SCYLLA_CONTACT_POINTS
              value: scylla-client.databases.svc.cluster.local
            - name: SCYLLA_LOCAL_DC
              value: datacenter1
            - name: SCYLLA_KEYSPACE
              value: tessaro_admin
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: tessaro-config
                  key: cors-allowed-origins
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
