apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: knative-serving
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: knative-repo
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  targetNamespace: knative-serving
  values:
    namespaceOverride: knative-serving
    controller:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
    autoscaler:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
