services:
  litefs:
    image: flyio/litefs:0.5
    container_name: litefs
    command: ["litefs", "mount", "--config", "/etc/litefs.yml"]
    environment:
      LITEFS_NODE_ID: dev-primary
      LITEFS_SHARED_SECRET: dev-litefs-secret
    volumes:
      - ./litefs.yml:/etc/litefs.yml:ro
      - litefs-data:/var/lib/litefs
      - litefs-mount:/litefs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

  seaweedfs:
    image: chrislusf/seaweedfs:3.66
    container_name: seaweedfs
    command: ["server", "-s3", "-dir", "/data", "-volume.max=1"]
    environment:
      WEED_S3_ROOT_USER: devaccesskey
      WEED_S3_ROOT_PASSWORD: devsecretkey
    volumes:
      - seaweed-data:/data

volumes:
  litefs-data:
  litefs-mount:
  seaweed-data:
