apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry
resources:
  - registry-pvc.yaml
  - registry-deployment.yaml
  - registry-service.yaml
  - registry-ingressroute.yaml
