apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  labels:
    app.kubernetes.io/name: container-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
