apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  labels:
    app.kubernetes.io/name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
