apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bootstrap
  labels:
    app.kubernetes.io/name: minio
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-root-credentials
                  key: username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-root-credentials
                  key: password
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              until /usr/bin/mc alias set tessaro-minio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "Waiting for MinIO..."
                sleep 5
              done
              /usr/bin/mc mb tessaro-minio/tessaro-profile-pictures || true
              /usr/bin/mc anonymous set download tessaro-minio/tessaro-profile-pictures || true
