apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app.kubernetes.io/name: users-api
    app.kubernetes.io/part-of: tessaro-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: users-api
      app.kubernetes.io/part-of: tessaro-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-api
        app.kubernetes.io/part-of: tessaro-admin
    spec:
      containers:
        - name: users-api
          image: registry.tessaro.dino.home/apps/users-api:v0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
            - name: HOST
              value: 0.0.0.0
            - name: SCYLLA_CONTACT_POINTS
              value: scylla-client.databases.svc.cluster.local
            - name: SCYLLA_LOCAL_DC
              value: datacenter1
            - name: SCYLLA_KEYSPACE
              value: tessaro_admin
            - name: CORS_ALLOWED_ORIGINS
              value: http://192.168.1.21:31173
          ports:
            - containerPort: 4000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
