apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: tessaro-users
spec:
  createingress: false
  functionref:
    functionweights: null
    name: tessaro-users
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /tessaro/users
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /tessaro/users
