apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - scylla-service.yaml
  - scylla-client-service.yaml
  - scylla-statefulset.yaml
  - scylla-schema-job.yaml
