apiVersion: v1
kind: Service
metadata:
  name: scylla-client
  labels:
    app.kubernetes.io/name: scylla
spec:
  type: ClusterIP
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
  selector:
    app.kubernetes.io/name: scylla
