apiVersion: v1
kind: Service
metadata:
  name: scylla
  labels:
    app.kubernetes.io/name: scylla
spec:
  clusterIP: None
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
  selector:
    app.kubernetes.io/name: scylla
