apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylla
  labels:
    app.kubernetes.io/name: scylla
spec:
  serviceName: scylla
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:2025.3
          env:
            - name: SCYLLA_AUTO_CONF
              value: "1"
          ports:
            - containerPort: 9042
              name: cql
          readinessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 8
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: scylla-data
              mountPath: /var/lib/scylla
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1024
        fsGroupChangePolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: scylla-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
