apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
  annotations:
    knative.dev/example-checksum: "1"
data:
  svc.cluster.local: ""
