apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: net-kourier
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: net-kourier
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: knative-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: kourier-system
  values:
    namespaceOverride: kourier-system
    service:
      type: LoadBalancer
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
