apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tessaro
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com/EyalRo/Tessaro.git
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tessaro-cluster
  namespace: flux-system
spec:
  interval: 5m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tessaro
  path: ./platform/flux/clusters/home
  decryption:
    provider: sops
    secretRef:
      name: sops-age
