apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    app.kubernetes.io/name: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: object-storage
  labels:
    app.kubernetes.io/name: object-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: scylla-operator
  labels:
    app.kubernetes.io/name: scylla-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    app.kubernetes.io/name: knative-eventing
---
apiVersion: v1
kind: Namespace
metadata:
  name: kourier-system
  labels:
    app.kubernetes.io/name: kourier-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
