name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  api-server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run API server tests
        working-directory: services/api-server
        run: deno task test
